name: Ansible Lint CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip install ansible ansible-lint

      - name: Rodar ansible-lint no playbook
        run: ansible-lint nginx_setup.yml

